### ISSUE TITLE
Replace parts with grunt-bump

### ISSUE THREAD

**Issue by eddiemonge** [geddski/grunt-release#85]
Seems like there is a lot of overlap between this and `grunt-bump`. What if this used grunt-bump to handle 1-6 of https://github.com/geddski/grunt-release#repetition-killed-the-cat and then this primarily did the release parts (7-8)?

**Comment by drublic** [comment]
Thanks for the idea.

What value does it add to our package? This would mean we would need to wait for grunt-bump to merge in changes we have. Also this means we need to adept their API in some way which seems to a breaking change.

I would not consider this for the foreseeable future. grunt-bump should either handle all of the mentioned things or we should make steps 1 to 6 better within our code, if we don't match what grunt-bump does.
Yes, we now have two different packages that handle kind of the same stuff but I think this is OK since we do other stuff than they do.

Please let me know if you think I am wrong here.

**Comment by eddiemonge** [comment]
I was just saying that it seems like a lot of duplicated effort to accomplish the same things.

**Comment by drublic** [comment]
Yes. And I think you are right with this statement. But still, there are different things that get handled. I'd love to include everything that is missing from grunt-bump into grunt-release.

Hope you are down with this :) Thanks for the feedback!
